{% set name = "pyuvdata" %}
{% set version = "2.2.3" %}
{% set sha256 = "9e6dfaaafa75390d04e1c1387c58c70fcd89e048e000f97af9dbbafcb4960c73" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - warnings.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<=36]]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - astropy >=4.2.1
    - cython >=0.23
    - h5py
    - numpy >=1.18.*  # pyuvdata requires this
    - pip
    - pyerfa >=2.0
    - pytest-runner
    - python
    - scipy
    - setuptools
    - setuptools_scm
  run:
    - astropy >=4.2.1
    - h5py
    - {{ pin_compatible('numpy') }}
    - pyerfa >=2.0
    - python
    - scipy
    - setuptools_scm

test:
  requires:  # novas and novas_de405 are not included because they aren't on conda
    - git
    - astropy-healpix
    - astroquery
    - cython >=0.23
    - pytest >=6.2
    - pytest-cases >=3
    - pytest-xdist
    - python-casacore  # [not win]
    - pyyaml
    - setuptools_scm
  imports:
    - pyuvdata
  commands:
    - pytest -vv -s --pyargs pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: an interface for astronomical interferometeric datasets in python
  doc_url: https://pyuvdata.readthedocs.io
  dev_url: https://github.com/RadioAstronomySoftwareGroup/pyuvdata

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
