{% set name = "pyuvdata" %}
{% set version = "1.3.1" %}
{% set sha256 = "71f2b56b7301d2158a31231673001de69406c8014996400093dcae45b3ef574f" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=files.txt
  skip: true  # [win or py3k]

requirements:
  build:
    - aipy >=2.1.6
    - astropy >=1.2
    - numpy >=1.11
    - pyephem
    - python <3
    - scipy
    - setuptools
  run:
    - aipy >=2.1.6
    - astropy >=1.2
    - numpy >=1.11
    - pyephem
    - python <3
    - scipy

test:
  requires:
    - healpy
    - nose
    - python-casacore
  imports:
    - pyuvdata
  commands:
    - nosetests pyuvdata

about:
  home: https://github.com/HERA-Team/pyuvdata
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Reading and writing interferometric data sets.'

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
