{% set name = "pyuvdata" %}
{% set version = "1.3.2" %}
{% set sha256 = "ecde02a54c72f185f29ba43b4bec3fe515d6280c62628978945756f2bced62f9" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - six >=1.10
    - astropy >=2.0
    # we require at least numpy 1.14 in pyuvdata
    - numpy 1.14.*
    - pip
    - python
    - scipy
    - setuptools
  run:
    - six >=1.10
    - astropy >=2.0
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  requires:
    - healpy
    - nose
    - python-casacore
    - h5py
  imports:
    - pyuvdata
  commands:
    - nosetests pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'an interface for astronomical interferometeric datasets in python'

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
