{% set name = "pyuvdata" %}
{% set version = "2.4.4" %}
{% set sha256 = "1b871d1f8456e172a84a5247a15949932a2f28fb56acdcac5ae544a212319d24" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - warnings.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<=39]]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - astropy >=6.0
    - cython >=3.0
    - docstring_parser >=0.15
    - h5py >=3.4
    - numpy  # pyuvdata needs >=1.23
    - pip
    - pyerfa >=2.0.1.1
    - python
    - scipy >=1.7.3
    - setuptools >=61
    - setuptools_scm <7.0|>=7.0.3
  run:
    - astropy >=6.0
    - docstring_parser >=0.15
    - h5py >=3.4
    - {{ pin_compatible('numpy') }}
    - pyerfa >=2.0.1.1
    - python
    - scipy >=1.7.3
    - setuptools_scm <7.0|>=7.0.3

test:
  requires:  # lunarsky, novas, and novas_de405 are not included because they aren't on conda
    - git
    - astropy-healpix >=1.0.2
    - astroquery >=0.4.4
    - hdf5plugin >= 3.2.0
    - cython >=3.0
    - pytest >=6.2.5
    - pytest-cases >=3.8.3
    - pytest-xdist
    - python-casacore >=3.5.2  # [not win]
    - pyyaml >=5.4.1
    - setuptools_scm <7.0|>=7.0.3
  imports:
    - pyuvdata
  commands:
    - pytest -vv -s --pyargs pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: an interface for astronomical interferometeric datasets in python
  doc_url: https://pyuvdata.readthedocs.io
  dev_url: https://github.com/RadioAstronomySoftwareGroup/pyuvdata

extra:
  recipe-maintainers:
    - plaplant
    - bhazelton
    - pkgw
