{% set name = "pyuvdata" %}
{% set version = "1.3" %}
{% set sha256 = "e7a103b6fcc36ee56b658c1497b9b62446babcab4730993c99064dcc654451f5" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=files.txt
  skip: true  # [win or py3k]

requirements:
  build:
    - six >=1.10
    - astropy >=2.0
    - numpy >=1.14
    - python
    - scipy
    - setuptools
  run:
    - six >=1.10
    - astropy >=2.0
    - numpy >=1.14
    - python
    - scipy

test:
  requires:
    - healpy
    - nose
    - python-casacore
    - h5py
  imports:
    - pyuvdata
  commands:
    - python setup.py build_ext --force --inplace
    - nosetests pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'an interface for astronomical interferometeric datasets in python'

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
