{% set name = "pyuvdata" %}
{% set version = "3.2.1" %}
{% set sha256 = "e4d6655d021fd95a1fa358834e15adf5cf55a0df0611f4e7bb765e6a9bde2b49" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<=39]]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - astropy-base >=6.0
    - cython >=3.0
    - docstring_parser >=0.15
    - h5py >=3.4
    - numpy  # pyuvdata needs >=1.23
    - pip
    - pyyaml >=5.4.1
    - pyerfa >=2.0.1.1
    - python
    - scipy >=1.8
    - setuptools >=64
    - setuptools_scm >=8.1
  run:
    - astropy-base >=6.0
    - docstring_parser >=0.15
    - h5py >=3.4
    - pyyaml >=5.4.1
    - pyerfa >=2.0.1.1
    - python
    - scipy >=1.8
    - setuptools_scm >=8.1

test:
  requires:  # lunarsky, novas, and novas_de405 are not included because they aren't on conda
    - git
    - astropy-healpix >=1.0.2
    - astroquery >=0.4.4
    - hdf5plugin >=3.2.0
    - cython >=3.0
    - pytest >=8.2
    - pytest-cases >=3.8.3
    - pytest-xdist
    - python-casacore >=3.5.2  # [not win]
  source_files: tests
  imports:
    - pyuvdata
  commands:
    - pytest -vv -s tests

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: an interface for astronomical interferometeric datasets in python
  doc_url: https://pyuvdata.readthedocs.io
  dev_url: https://github.com/RadioAstronomySoftwareGroup/pyuvdata

extra:
  recipe-maintainers:
    - plaplant
    - bhazelton
    - pkgw
